#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/s5e9945

PRODUCT_COPY_FILES += \
    vendor/samsung/s5e9945/proprietary/recovery/root/lib/firmware/sgpu/vangogh_lite_unified_evt1.bin:$(TARGET_COPY_OUT_RECOVERY)/root/lib/firmware/sgpu/vangogh_lite_unified_evt1.bin \
    vendor/samsung/s5e9945/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/samsung/s5e9945/proprietary/vendor/etc/LVACFS_Configuration.txt:$(TARGET_COPY_OUT_VENDOR)/etc/LVACFS_Configuration.txt \
    vendor/samsung/s5e9945/proprietary/vendor/etc/enn/custom_mode_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/enn/custom_mode_config.json \
    vendor/samsung/s5e9945/proprietary/vendor/etc/gnss/ca.pem:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/ca.pem \
    vendor/samsung/s5e9945/proprietary/vendor/etc/hdr_samsung_mx.key:$(TARGET_COPY_OUT_VENDOR)/etc/hdr_samsung_mx.key \
    vendor/samsung/s5e9945/proprietary/vendor/etc/hts.json:$(TARGET_COPY_OUT_VENDOR)/etc/hts.json \
    vendor/samsung/s5e9945/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service-qti.rc \
    vendor/samsung/s5e9945/proprietary/vendor/etc/init/android.hardware.gatekeeper-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper-service.rc \
    vendor/samsung/s5e9945/proprietary/vendor/etc/init/android.hardware.neuralnetworks-service-enn.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks-service-enn.rc \
    vendor/samsung/s5e9945/proprietary/vendor/etc/init/android.hardware.security.keymint-service.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.samsung.rc \
    vendor/samsung/s5e9945/proprietary/vendor/etc/init/dmd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dmd.rc \
    vendor/samsung/s5e9945/proprietary/vendor/etc/init/enn-lazy.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/enn-lazy.rc \
    vendor/samsung/s5e9945/proprietary/vendor/etc/init/vendor.samsung.hardware.camera.provider-service_64.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.camera.provider-service_64.rc \
    vendor/samsung/s5e9945/proprietary/vendor/etc/init/vendor.samsung.hardware.gnss-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.gnss-service.rc \
    vendor/samsung/s5e9945/proprietary/vendor/etc/nfc/sec_s3nsen6_hwreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/sec_s3nsen6_hwreg.bin \
    vendor/samsung/s5e9945/proprietary/vendor/etc/nfc/sec_s3nsen6_swreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/sec_s3nsen6_swreg.bin \
    vendor/samsung/s5e9945/proprietary/vendor/etc/sound_trigger_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sound_trigger_info.xml \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/00_generic_xtalk_shape.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/00_generic_xtalk_shape.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/APBargeIn_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APBargeIn_AUDIO_SLSI.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/APBiBF_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APBiBF_AUDIO_SLSI.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/APDVTX_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APDVTX_AUDIO_SLSI.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/AP_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/AP_AUDIO_SLSI.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/Data.msc:$(TARGET_COPY_OUT_VENDOR)/firmware/Data.msc \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/MFC_DOF_FE_O2_ROOT_ENN_Front.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/MFC_DOF_FE_O2_ROOT_ENN_Front.nnc \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/MFC_DOF_FE_O2_ROOT_ENN_Rear.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/MFC_DOF_FE_O2_ROOT_ENN_Rear.nnc \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/MFC_DOF_MV_B2_O2_ROOT_ENN_Front.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/MFC_DOF_MV_B2_O2_ROOT_ENN_Front.nnc \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/MFC_DOF_MV_B2_O2_ROOT_ENN_Rear.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/MFC_DOF_MV_B2_O2_ROOT_ENN_Rear.nnc \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/MFC_DOF_MV_B3_O2_ROOT_ENN_Front.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/MFC_DOF_MV_B3_O2_ROOT_ENN_Front.nnc \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/MFC_DOF_MV_B3_O2_ROOT_ENN_Rear.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/MFC_DOF_MV_B3_O2_ROOT_ENN_Rear.nnc \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/MFC_DOF_MV_B4_O2_ROOT_ENN_Front.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/MFC_DOF_MV_B4_O2_ROOT_ENN_Front.nnc \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/MFC_DOF_MV_B4_O2_ROOT_ENN_Rear.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/MFC_DOF_MV_B4_O2_ROOT_ENN_Rear.nnc \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/MSL.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/MSL.nnc \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/OD_V3.4.10_11_13_QVGA_ROOT_ENN_BGRA.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/OD_V3.4.10_11_13_QVGA_ROOT_ENN_BGRA.nnc \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/OD_V3.5.3_09_26_VGA_ROOT_ENN_BGRA.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/OD_V3.5.3_09_26_VGA_ROOT_ENN_BGRA.nnc \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/SoundAlive.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SoundAlive.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/a2dpcom.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a2dpcom.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/abox_solution.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_solution.conf \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/abox_system.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_system.conf \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/abox_tplg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/abox_tplg.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.conf \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/avsyncmix.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/avsyncmix.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/bidirmic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bidirmic.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/calliope_dram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_dram.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/compress_capture.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/compress_capture.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/cs35l43-bot-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l43-bot-dsp1-spk-prot.wmfw \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/cs35l43-rcv-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l43-rcv-dsp1-spk-prot.wmfw \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/cs40l26-a2h.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-a2h.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/cs40l26-svc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/cs40l26-svc1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc1.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/cs40l26-svc2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc2.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/cs40l26-svc3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc3.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/default_configuration.dof.front.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/default_configuration.dof.front.cfg.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/default_configuration.dof.rear.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/default_configuration.dof.rear.cfg.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/default_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/default_configuration.flm.cfg.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/dolby.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dolby.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/dsp_gkt.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_gkt.xml \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/dsp_ivp_dm.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_ivp_dm.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/dsp_ivp_pm.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_ivp_pm.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/dsp_reloc_rules.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_reloc_rules.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/eis_stab_strength.json:$(TARGET_COPY_OUT_VENDOR)/firmware/eis_stab_strength.json \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/gnss/firmware_signed_e1sksx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_e1sksx.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/gnss/firmware_signed_e1sxxx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_e1sxxx.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/gnss/firmware_signed_e2sksx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_e2sksx.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/gnss/firmware_signed_e2sxxx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_e2sxxx.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/gnss/firmware_signed_r12sjpnx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_r12sjpnx.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/gnss/firmware_signed_r12skdix.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_r12skdix.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/gnss/firmware_signed_r12sksx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_r12sksx.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/gnss/firmware_signed_r12sxxx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_r12sxxx.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/gnss/firmware_signed_r12szhx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_r12szhx.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/hmtbtfw20.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/hmtbtfw20.tlv \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/hmtnv20.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/hmtnv20.b20 \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/hmtnv20.b39:$(TARGET_COPY_OUT_VENDOR)/firmware/hmtnv20.b39 \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/hmtnv20.b3c:$(TARGET_COPY_OUT_VENDOR)/firmware/hmtnv20.b3c \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/icc_profile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/icc_profile.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/is_mcu_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/is_mcu_fw.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/kiwi/amss20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/amss20.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/kiwi/phy_ucode20.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/phy_ucode20.elf \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/kiwi/qdss_trace_config_v2.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/qdss_trace_config_v2.cfg \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/kiwi/regdb.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/regdb.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/lc3dec.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lc3dec.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/lc3enc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lc3enc.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/libivp.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/libivp.elf \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/liblog.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/liblog.elf \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/listenbackeffect.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/listenbackeffect.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/max77775-extra-fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/max77775-extra-fw.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/max77775-fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/max77775-fw.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/mfc/mfc_fw_flash_cps4038.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc/mfc_fw_flash_cps4038.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/nfc/sec_s3nsen6_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nfc/sec_s3nsen6_firmware.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/rvpdec.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/rvpdec.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/rvpenc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/rvpenc.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/rxse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/rxse.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/sb_ll.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_ll.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/sb_music.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_music.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/sb_others.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_others.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/sectiongraph_tplg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sectiongraph_tplg.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/sectiongraph_tplg.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/sectiongraph_tplg.conf \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/secure_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/secure_configuration.flm.cfg.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/setfile_3k1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_3k1.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/setfile_3lu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_3lu.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/setfile_gn3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_gn3.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/setfile_imx564.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_imx564.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/txse1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/txse1.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/txse2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/txse2.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/uNPU.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/uNPU.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/video_cnn.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/video_cnn.nnc \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/vl53l8.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/vl53l8.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/volctrl.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/volctrl.bin \
    vendor/samsung/s5e9945/proprietary/vendor/firmware/volumemonitor.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/volumemonitor.bin \
    vendor/samsung/s5e9945/proprietary/vendor/tee/00000000-0000-0000-0000-42494f535542:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-42494f535542 \
    vendor/samsung/s5e9945/proprietary/vendor/tee/00000000-0000-0000-0000-46494e474502:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-46494e474502 \
    vendor/samsung/s5e9945/proprietary/vendor/tee/00000000-0000-0000-0000-4d5053545549:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-4d5053545549 \
    vendor/samsung/s5e9945/proprietary/vendor/tee/00000000-0000-0000-0000-4d704e434954:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-4d704e434954 \
    vendor/samsung/s5e9945/proprietary/vendor/tee/00000000-0000-0000-0000-4d70536b566e:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-4d70536b566e \
    vendor/samsung/s5e9945/proprietary/vendor/tee/00000000-0000-0000-0000-4d7073617574:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-4d7073617574 \
    vendor/samsung/s5e9945/proprietary/vendor/tee/00000000-0000-0000-0000-5345435f4652:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-5345435f4652 \
    vendor/samsung/s5e9945/proprietary/vendor/tee/00000000-0000-0000-0000-6d706f667376:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-6d706f667376 \
    vendor/samsung/s5e9945/proprietary/vendor/tee/tui/resolution_common/ID00000100:$(TARGET_COPY_OUT_VENDOR)/tee/tui/resolution_common/ID00000100

PRODUCT_PACKAGES += \
    gnss_aidl_lib \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.bluetooth@1.1-impl-qti \
    audio.primary.s5e9945 \
    gatekeeper.s5e9945 \
    sound_trigger.primary.s5e9945 \
    vulkan.samsung \
    libExtIDRC \
    libExtIRTA \
    libIMUSensor \
    libIRTA \
    libImageFormatConverter \
    libOpenCL \
    libSamsungPostProcessConvertor \
    libTsAwb_front \
    libTsAwb_rear \
    libTsPrc_front \
    libTsPrc_rear \
    libVendorSemDataProps \
    libVendorSemTelephonyProps \
    lib_SamsungRec_08020 \
    lib_SoundAlive_3DPosition_ver202 \
    lib_SoundAlive_AlbumArt_ver105 \
    lib_SoundAlive_SRC384_ver320 \
    lib_SoundAlive_play_plus_ver800 \
    lib_SoundBooster_ver2000 \
    lib_lvacfs \
    lib_profiler \
    lib_soundaliveresampler \
    libalsautils_sec \
    libaudio-ril \
    libaudioparamupdate \
    libaudioproxy2 \
    libaudioroute_samsung \
    libcav \
    libcdi \
    libcdi_wrapper \
    libcommon \
    libcrane_compiler \
    libdove_compiler \
    libeagle_compiler \
    libegis_fp_normal_sensor_test \
    libeis_core \
    libengmode_client \
    libenn_common_utils \
    libenn_cpu_operators \
    libenn_engine \
    libenn_engine_lib \
    libenn_model \
    libenn_public_api_cpp_lib \
    libenn_user_driver_cpu \
    libenn_user_driver_gpu \
    libenn_user_driver_gpu_lib \
    libenn_user_driver_unified \
    libenn_user_lib \
    libexynos_logger \
    libexynos_profiler \
    libexynos_sensor_interface \
    libfloatingfeature \
    libgf_in_system_lib \
    libgraphgen \
    libgraphgen_api \
    libhdrwrapper \
    libhermes_bdbridge \
    libhermes_cred \
    libhwjsqz \
    libhwvault \
    libipv \
    libir \
    libisa \
    libisa_generator \
    liblastaboxmsg \
    libmpbase \
    libncp_wrapper \
    libnpu_compiler \
    libprofileparamstorage \
    libqfp_sensortest \
    librechdr10plus.plugin \
    librechdr10plus \
    libril_sem \
    libsait_npu_compiler \
    libsamsungcamerahal \
    libsamsungcamerahalutils \
    libsamsungcamerahwl_impl \
    libsec-ril \
    libsec_esek \
    libsec_semHalTlc \
    libsec_semRil \
    libsecaudiocoreutils \
    libsecaudioinfo \
    libsecaudiolevel \
    libsecnativefeature \
    libsecril-client \
    libsehbluetooth_audio_session_aidl \
    libsemnativecarrierfeature \
    libsemseg \
    libsensorlistener \
    libsfp_sensor \
    libsfp_teegw \
    libshctrl \
    libskeymint10device \
    libskeymint_cli \
    libspatializerparamstorage \
    libspeakercalibration \
    libspictrl \
    libsynaFpSensorTestNwd \
    libteecl \
    libtinyalsa_samsung \
    libtriplecam_video_optical_zoom \
    libtriplepreview_interface \
    libuniapi \
    libuniplugin \
    libuuid_vendor \
    libvdis_core \
    libveriben_lib \
    libvkmanager_vendor \
    libvpl \
    libvpl_dof \
    libwrappergps \
    sensors.sensorhub \
    libaudioeffectoffload \
    libmyspace \
    vendor.samsung.hardware.biometrics.fingerprint-V1-ndk \
    vendor.samsung.hardware.bluetooth.audio-V2-ndk \
    vendor.samsung.hardware.bluetooth@2.0 \
    vendor.samsung.hardware.camera.device-V1-ndk \
    vendor.samsung.hardware.camera.provider-V1-ndk \
    vendor.samsung.hardware.gnss-V3-ndk \
    vendor.samsung.hardware.keymint-V3-ndk \
    vendor.samsung.hardware.radio-V1-ndk \
    vendor.samsung.hardware.radio.bridge-V1-ndk \
    vendor.samsung.hardware.radio.channel-V1-ndk \
    vendor.samsung.hardware.radio.data-V1-ndk \
    vendor.samsung.hardware.radio.messaging-V1-ndk \
    vendor.samsung.hardware.radio.sim-V1-ndk \
    vendor.samsung.hardware.security.drk-V1-ndk \
    vendor.samsung.hardware.security.drk@2.0 \
    vendor.samsung.hardware.security.hermes-V1-ndk \
    vendor.samsung.hardware.thermal-V1-ndk \
    vendor.samsung.hardware.thermal@1.0 \
    vendor.samsung.libcolor.hardware \
    vendor.samsung_slsi.hardware.enn_aidl-V1-ndk \
    com.google.android.widevine.nonupdatable \
    HotwordEnrollmentOKGoogleEx4CORTEXM55 \
    HotwordEnrollmentXGoogleEx4CORTEXM55 \
    com.android.hotwordenrollment.common.util \
    android.hardware.neuralnetworks-service-enn.xml \
    enn-default.xml \
    iweaver_aidl_v2_manifest.xml \
    vendor.samsung.hardware.camera.provider-service.xml \
    vendor.samsung.hardware.radio_manifest_2_34.xml \
    vendor.samsung.hardware.sehradio_manifest_2_34.xml \
    dmd \
    gflow \
    gperf \
    hermesd \
    htsd \
    android.hardware.bluetooth@1.1-service-qti \
    android.hardware.gatekeeper-service \
    android.hardware.neuralnetworks-service-enn \
    android.hardware.security.keymint-service.samsung \
    gps \
    gpsd_K43 \
    rild \
    vendor.samsung.hardware.camera.provider-service_64 \
    vendor.samsung.hardware.gnss-service \
    vendor.samsung_slsi.hardware.enn_aidl-service \
    tzdaemon \
    tzts_daemon
